'use client';
import { useState } from 'react';
import type { Address } from 'viem';
import { useLive } from './LiveProvider';
import { canConfirmProposal, type Data } from './client';
import { DateText, Details, Form, money, units, seconds } from './ui';

export function LeaseActions({ data, chain, caseId, refresh, view }: { data: Data; chain: Data; caseId?: string; refresh: () => void; view: string }) {
  const { request, propose, run, busy, wallet } = useLive();
  const id = data.leaseId ?? data.id, address = data.contractAddress as Address;
  const [saved, setSaved] = useState<Data | null>(null);
  const role = data.role, t = chain.terms, a = chain.accounting, c = chain.activeCase, s = chain.schedule;
  const time = Number(chain.chainTime), phase = Number(chain.phase), cid = BigInt(c.caseId);
  const action = (title: string, functionName: string, args: unknown[] = [], explanation = title) => propose({ title, explanation, address, functionName, args, leaseId: id });
  const prepared = (value: Data, expected: string[], title: string) => {
    setSaved(value);
    if (!value.transaction || !expected.includes(value.transaction.functionName)) throw new Error('The returned wallet action does not match this operation.');
    action(title, value.transaction.functionName, value.transaction.args, 'The private text is saved. Review the amounts, material versions and deadlines before confirming its on-chain submission.');
  };
  const statement = async (body: Data, expected: string[], title: string) => prepared(await request(`/api/leases/${id}/statements`, body), expected, title);
  const button = (title: string, name: string, args: unknown[] = [], enabled = true, explanation = title) => <button className="btn" disabled={busy || !enabled} onClick={() => void run(async () => action(title, name, args, explanation))}>{title}</button>;
  const party = role === 'T' || role === 'L';
  const active = BigInt(a.fundedAmount) > 0n && time < Number(t.hardEndAt);
  const show = (...sections: string[]) => sections.includes(view);
  return <>
    {saved && <section className="glass glass-pad"><p>The text is saved. If signing was cancelled, confirm again to submit it. Saving does not make it effective on-chain.</p><button className="btn" disabled={busy} onClick={() => void run(async () => prepared(saved, [saved.transaction.functionName], 'Submit the saved record'))}>Continue submitting the saved record</button></section>}
    {show('fund', 'overview') && <section className="glass glass-pad"><h2>Terms & deposit</h2><p>{data.terms.termsText}</p><p>Fixed tenant {t.tenant}; Fixed landlord {t.landlord}</p><p>Deposit {money(t.depositAmount)}; lease ends <DateText value={t.leaseEndAt} />; Final exit <DateText value={t.hardEndAt} /></p><p>If both resolvers time out, disputed amounts without an effective award return to the tenant under the agreed policy. Established deductions remain valid. The contract cannot verify whether evidence is true.</p><Details title="Full terms & service profile" value={{ privateTerms: data.terms, chainTerms: t }} />
      {role === 'T' && phase === 0 && button('Accept the full terms', 'acceptTerms', [data.commitment])}
      {role === 'T' && phase === 1 && <><button className="btn" disabled={busy} onClick={() => void run(async () => propose({ title: `Approve ${money(t.depositAmount)}`, explanation: 'Allow this deposit contract to transfer exactly this amount. Approval is not funding; confirm the deposit separately.', address: t.token, kind: 'token', functionName: 'approve', args: [address, BigInt(t.depositAmount)] }))}>Approve {money(t.depositAmount)}</button>{button(`Confirm deposit of ${money(t.depositAmount)}`, 'fund', [BigInt(t.depositAmount)], BigInt(chain.allowance) >= BigInt(t.depositAmount), `Transfer from the tenant to ${address} exactly ${money(t.depositAmount)}.`)}</>}
      {role === 'T' && BigInt(chain.allowance) > 0n && <button className="btn" disabled={busy} onClick={() => void run(async () => propose({ title: 'Revoke remaining allowance', explanation: 'Set this contract’s MockUSD allowance to zero. This does not affect an existing deposit.', address: t.token, kind: 'token', functionName: 'approve', args: [address, 0n] }))}>Revoke remaining allowance</button>}
      {party && phase < 2 && button('Cancel the unfunded lease', 'cancelUnfunded')}
      {phase < 2 && time >= Number(t.acceptDeadline) && button('Expire the unfunded lease', 'expireUnfunded')}
    </section>}
    {show('overview', 'settlement', 'case', 'claims') && <section className="glass glass-pad"><h2>Settlement & withdrawals</h2><p>Deadlines use confirmed block time. The page cannot change them. Allocation and withdrawal are separate transactions.</p>
      {[2, 3, 4].includes(phase) && time >= Number(t.leaseEndAt) && button('Start scheduled settlement', 'startScheduledSettlement')}
      {phase === 5 && time >= Number(s.claimDeadline) && button('Close claims & allocate undisputed funds', 'closeClaims')}
      {phase === 6 && time >= Number(s.responseDeadline) && BigInt(a.unallocated) > 0n && button('Open the claims case', 'openClaimCase')}
      {c.exists && Number(c.phase) === 2 && time >= Number(c.challengeDeadline) && button('Finalize the unchallenged primary decision', 'finalizePrimary', [cid])}
      {c.exists && Number(c.phase) === 1 && time >= Number(c.primaryDeadline) && button('Escalate a primary timeout to fallback', 'escalateTimeout', [cid])}
      {c.exists && Number(c.phase) === 3 && time >= Number(c.fallbackDeadline) && button('Mark fallback service timeout', 'markServiceTimeout', [cid])}
      {c.exists && Number(c.phase) === 4 && time >= Number(c.timeoutAt) && button('Allocate under the fixed timeout policy', 'finalizeTimeout', [cid])}
      {BigInt(a.unallocated) > 0n && time >= Number(t.hardEndAt) && button('Execute final exit', 'expireEscrow')}
      {party && BigInt(role === 'T' ? a.tenantCredit : a.landlordCredit) > 0n && button(`Withdraw ${money(role === 'T' ? a.tenantCredit : a.landlordCredit)}`, 'withdraw', [], true, `Pay only the fixed ${role === 'T' ? 'Tenant' : 'Landlord'} address. A confirmed receipt is required.`)}
      <button className="btn" disabled={busy} onClick={refresh}>Refresh on-chain state</button>
    </section>}
    {show('checkout') && party && active && phase === 2 && <Form title="Request early checkout" fields={[{ name: 'actualAt', label: 'Actual checkout date', type: 'datetime-local' }, { name: 'documentId', label: 'Checkout document ID (copy from the materials list)' }, { name: 'version', label: 'Document version', type: 'number', value: '1' }, { name: 'reason', label: 'Checkout explanation (at least 20 characters)', type: 'textarea', minLength: 20 }]} submit="Save & review the checkout request" onSubmit={async v => statement({ kind: 'checkout', actualAt: seconds(v.actualAt), reason: v.reason, documents: [{ documentId: v.documentId, version: Number(v.version) }] }, ['requestCheckout'], 'Confirm the early checkout request')} />}
    {show('checkout') && party && active && phase === 3 && <section className="glass glass-pad"><h2>Respond to early checkout</h2><p>Response deadline <DateText value={chain.checkout.responseDeadline} />. Early checkout opens the claim window; it does not allocate the deposit.</p>{chain.checkout.requester.toLowerCase() !== wallet?.address.toLowerCase() && time < Number(chain.checkout.responseDeadline) && <>{button('Agree to this checkout', 'respondCheckout', [true, chain.checkout.evidenceHash])}{button('Dispute this checkout', 'respondCheckout', [false, chain.checkout.evidenceHash])}</>}{(chain.checkout.responded || time >= Number(chain.checkout.responseDeadline)) && button('Open a checkout case', 'openCheckoutCase')}</section>}
    {show('claims') && role === 'L' && phase === 5 && time < Number(s.claimDeadline) && chain.claims.length === 0 && <ClaimsForm leaseId={id} deposit={t.depositAmount} prepare={v => prepared(v, ['submitClaims'], 'Confirm the entire one-time deduction list')} />}
    {show('claims', 'case') && chain.claims.length > 0 && <section className="glass glass-pad"><h2>Deductions & responses</h2><p>Claim deadline <DateText value={s.claimDeadline} />; Response deadline <DateText value={s.responseDeadline} />. Silence is not agreement. Accepting a deduction is irreversible.</p>{chain.claims.map((claim: Data) => <article key={claim.id}><h3>Item {claim.id} · {money(claim.amount)}</h3><p>{['No response', 'Accepted (see balances for allocation)', 'Disputed', 'Waived', 'Allocated'][Number(claim.status)]}</p>{role === 'T' && active && [5, 6].includes(phase) && time < Number(s.responseDeadline) && [0, 2].includes(Number(claim.status)) && <Form title={`Respond to item ${claim.id}`} fields={[{ name: 'accept', label: 'Response', options: [{ value: 'false', label: 'Dispute' }, { value: 'true', label: `Accept ${money(claim.amount)} (irreversible)` }] }, { name: 'reason', label: 'Reason (at least 20 characters)', type: 'textarea', minLength: 20 }, { name: 'documentId', label: 'Counter-evidence document ID (optional)', required: false }, { name: 'version', label: 'Counter-evidence version', type: 'number', value: '1' }]} submit="Save & review response" onSubmit={v => statement({ kind: 'claim-response', claimId: String(claim.id), accept: v.accept === 'true', reason: v.reason, documents: v.documentId ? [{ documentId: v.documentId, version: Number(v.version) }] : [] }, ['respondClaim'], `${v.accept === 'true' ? 'Accept' : 'Dispute'} item ${claim.id} · ${money(claim.amount)}`)} />}{role === 'L' && active && [5, 6].includes(phase) && [0, 2].includes(Number(claim.status)) && button(`Waive item ${claim.id}`, 'waiveClaim', [BigInt(claim.id)])}</article>)}</section>}
    {show('case') && party && active && c.exists && Number(c.phase) === 2 && time < Number(c.challengeDeadline) && <Form title="Request fallback resolution" fields={[{ name: 'reason', label: 'Challenge reason (at least 20 characters)', type: 'textarea', minLength: 20 }]} submit="Save & review challenge" onSubmit={v => statement({ kind: 'challenge', reason: v.reason, documents: [] }, ['challenge'], 'Challenge the primary decision and escalate')} />}
    {caseId && ['R', 'F'].includes(role) && active && <DecisionForm chain={chain} caseId={caseId} prepare={v => prepared(v, role === 'R' ? ['proposeDecision', 'proposeCheckoutDecision'] : ['resolveFallback', 'resolveFallbackCheckout'], role === 'R' ? 'Propose primary decision (effective after challenge window)' : 'Confirm fallback decision (effective immediately)')} />}
    {show('settlement') && party && active && BigInt(a.unallocated) > 0n && <><Form title="Settle the remaining deposit together" fields={[{ name: 'tenantShare', label: 'MockUSD for the tenant' }, { name: 'landlordShare', label: 'MockUSD for the landlord' }, { name: 'validUntil', label: 'Proposal expiry', type: 'datetime-local' }, { name: 'reason', label: 'Explanation (at least 20 characters)', type: 'textarea', minLength: 20 }]} submit="Save & review settlement proposal" onSubmit={v => { const tenantShare = units(v.tenantShare, a.unallocated), landlordShare = units(v.landlordShare, a.unallocated); if (BigInt(tenantShare) + BigInt(landlordShare) !== BigInt(a.unallocated)) throw new Error('The shares must add up to the current unallocated amount'); return statement({ kind: 'settlement', tenantShare, landlordShare, validUntil: seconds(v.validUntil), reason: v.reason }, ['proposeSettlement'], `Propose tenant ${money(tenantShare)} / Landlord ${money(landlordShare)}`); }}><p>This settles only the remaining deposit in RentBond. It does not automatically end the tenancy or waive other legal rights. Changes to amounts or case state invalidate the proposal.</p></Form>{BigInt(chain.proposal.proposalId) > 0n && <section className="glass glass-pad"><p>Proposal {chain.proposal.proposalId}: Tenant {money(chain.proposal.tenantShare)} / Landlord {money(chain.proposal.landlordShare)}; expires at <DateText value={chain.proposal.validUntil} /></p>{button('Accept this exact proposal from the other party', 'confirmSettlement', [BigInt(chain.proposal.proposalId)], canConfirmProposal(chain.proposal, a, time, wallet!.address, Number(t.hardEndAt), Number(c.timeoutAt)))}</section>}</>}
  </>;
}
function ClaimsForm({ leaseId, deposit, prepare }: { leaseId: string; deposit: string; prepare: (v: Data) => void }) {
  const { request } = useLive(); const [count, setCount] = useState(1);
  return <Form title="One-time deduction list (up to 10 items)" fields={Array.from({ length: count }, (_, i) => [
    { name: `category${i}`, label: `Item ${i + 1} Category`, options: [{ value: 'cleaning', label: 'Cleaning' }, { value: 'damage', label: 'Damage' }, { value: 'unpaid-rent', label: 'Unpaid rent' }, { value: 'utilities', label: 'Utilities' }, { value: 'other', label: 'Other' }] },
    { name: `amount${i}`, label: `Item ${i + 1} amount (MockUSD)` }, { name: `reason${i}`, label: 'Reason (at least 20 characters)', type: 'textarea', minLength: 20 }, { name: `clause${i}`, label: 'Relevant lease clause' }, { name: `document${i}`, label: 'Document ID (optional; explain if unavailable)', required: false }, { name: `version${i}`, label: 'Document version', type: 'number', value: '1' }, { name: `noEvidence${i}`, label: 'Basis for the claim if no document is available', required: false },
  ]).flat()} submit="Save list & review all amounts" onSubmit={async v => { const items = Array.from({ length: count }, (_, i) => ({ category: v[`category${i}`], amount: units(v[`amount${i}`], deposit), reason: v[`reason${i}`], clause: v[`clause${i}`], documents: v[`document${i}`] ? [{ documentId: v[`document${i}`], version: Number(v[`version${i}`]) }] : [], ...(v[`noEvidence${i}`] ? { noEvidenceReason: v[`noEvidence${i}`] } : {}) })); if (items.some(item => BigInt(item.amount) === 0n) || items.reduce((n, item) => n + BigInt(item.amount), 0n) > BigInt(deposit)) throw new Error('Each amount must be positive and the total cannot exceed the deposit'); prepare(await request('/api/claims/draft', { leaseId, items })); }}><p>After submission, you cannot add items or increase amounts. Review the complete list before confirming.</p><button className="btn" type="button" disabled={count >= 10} onClick={() => setCount(n => n + 1)}>Add an item</button><button className="btn" type="button" disabled={count <= 1} onClick={() => setCount(n => n - 1)}>Remove last item</button></Form>;
}
function DecisionForm({ chain, caseId, prepare }: { chain: Data; caseId: string; prepare: (v: Data) => void }) {
  const { request } = useLive(); const checkout = Number(chain.activeCase.caseType) === 1;
  const claims = chain.claims.filter((c: Data) => [0, 2].includes(Number(c.status))) as Data[];
  return <Form title="Itemized resolution" fields={[{ name: 'reason', label: 'Overall reasoning (at least 20 characters)', type: 'textarea', minLength: 20 }, ...(checkout ? [{ name: 'approved', label: 'Is early checkout established?', options: [{ value: 'false', label: 'Not established' }, { value: 'true', label: 'Established' }] }] : claims.flatMap(c => [{ name: `amount${c.id}`, label: `Item ${c.id} award to landlord (maximum ${money(c.amount)})` }, { name: `reason${c.id}`, label: `Item ${c.id} reasoning (at least 20 characters)`, type: 'textarea', minLength: 20 }]))]} submit="Save reasons & review decision" onSubmit={async v => prepare(await request(`/api/cases/${caseId}/decisions`, { reason: v.reason, documents: [], reasons: checkout ? [] : claims.map(c => ({ claimId: String(c.id), landlordAmount: units(v[`amount${c.id}`], c.amount), reason: v[`reason${c.id}`] })), ...(checkout ? { checkoutApproved: v.approved === 'true' } : {}) }))}><p>Evidence deadline <DateText value={chain.activeCase.evidenceDeadline} />; Primary deadline <DateText value={chain.activeCase.primaryDeadline} />; Challenge deadline <DateText value={chain.activeCase.challengeDeadline} />; Fallback deadline <DateText value={chain.activeCase.fallbackDeadline} />. Current permissions and deadlines are checked before submission and by the contract.</p></Form>;
}
