'use client';
import Link from 'next/link';
import { usePathname, useParams } from 'next/navigation';
import { useCallback, useEffect, useState } from 'react';
import { useLive } from './LiveProvider';
import { readLease, type Data } from './client';
import { Form, Details, History, ExportGas, DateText, money, units, seconds } from './ui';
import { LeaseActions } from './LeaseActions';
import { Materials } from './Materials';

export default function LivePage() {
  const { wallet, logout, generation, config, busy, message } = useLive();
  const path = usePathname(), params = useParams();
  return <div className="sky"><div className="stage live-stage"><div className="banner">{config.mode === 'local' ? 'Local test chain' : 'Monad testnet'} · MockUSD test assets have no cash value</div><header className="topbar"><Link href="/" className="brand">RentBond.</Link><nav className="actions"><Link href="/leases">My leases</Link><Link href="/resolver">Resolver</Link><Link href="/login">Account & recovery</Link>{wallet && <button className="btn" disabled={busy} onClick={logout}>Sign out</button>}</nav></header><main className="live-main" key={`${generation}:${path}`}>
    {path === '/' && <section className="glass glass-pad"><p className="kicker">PROGRAMMABLE DEPOSIT SETTLEMENT</p><h1>Dispute 200, not your entire 1,000 deposit.</h1><p>Review deductions one by one. Once the claim window closes, undisputed funds can be allocated and withdrawn.</p><p>Illustrative example: 1,000 MockUSD becomes 700 claimable by the tenant, 100 by the landlord, and 200 awaiting resolution. Your workspace shows actual contract balances.</p><p>Both parties must agree before funding. RentBond cannot recover deposits already paid to a landlord.</p><Link className="btn btn-primary" href="/leases">Open my leases</Link></section>}
    {!wallet || path === '/login' ? <Login /> : path.startsWith('/invite/') ? <Invite token={String(params.token)} /> : path === '/leases/new' ? <NewLease /> : path === '/resolver' ? <List resolver /> : params.id ? <LeasePage id={String(params.id)} caseId={params.caseId ? String(params.caseId) : undefined} /> : <List />}
    {busy && <p role="status">Processing. Please do not submit again. {message}</p>}
  </main></div></div>;
}
function Login() {
  const { login, wallet, busy, cancelLogin } = useLive(); const [expected, setExpected] = useState('');
  useEffect(() => { try { setExpected(localStorage.getItem('rentbond.original-address') ?? ''); } catch { /* Optional public metadata. */ } }, []);
  return <section className="glass glass-pad"><h1>Account & recovery</h1>{wallet ? <p>Signed in as {wallet.address}. Recover the original address to access existing leases. Sign out before changing accounts.</p> : <><p>Use a passkey to access your account and sign a login message for this site. Signing in does not accept lease terms or authorize deductions. Your signing session stays in memory and expires after 15 minutes.</p><button className="btn btn-primary" disabled={busy} onClick={() => void login('create', '')}>Create a passkey & sign in</button><label className="field">Original account address<input value={expected} onChange={e => setExpected(e.target.value)} autoComplete="off" /></label><button className="btn" disabled={busy || !/^0x[\da-f]{40}$/i.test(expected)} onClick={() => void login('restore', expected)}>Recover the original account</button><details><summary>Use an external wallet</summary><p>This does not replace any existing lease participant. Select the configured test network.</p><button className="btn" disabled={busy} onClick={() => void login('external', '')}>Connect wallet & sign in</button></details></>}{busy && <button className="btn" onClick={cancelLogin}>Cancel sign-in</button>}</section>;
}
function List({ resolver = false }: { resolver?: boolean }) {
  const { request, run, busy } = useLive(); const [rows, setRows] = useState<Data[]>([]), [cursor, setCursor] = useState<string | null>(null), [error, setError] = useState('');
  useEffect(() => { let alive = true; request(resolver ? '/api/resolver/cases' : '/api/leases').then(r => { if (alive) { setRows(r.items); setCursor(r.nextCursor); } }).catch(e => { if (alive) setError(e.message); }); return () => { alive = false; }; }, [request, resolver]);
  return <section className="glass glass-pad"><h1>{resolver ? 'Your assigned cases' : 'My leases'}</h1>{error && <p role="alert">{error}</p>}{!resolver && <Link className="btn" href="/leases/new">Create a lease draft</Link>}{!rows.length && !error && <p>No records yet. Resolvers only see cases currently assigned to them.</p>}<ul>{rows.map(r => <li key={r.id}><Link href={resolver ? `/leases/${r.leaseId}/cases/${r.id}` : `/leases/${r.id}`}>{r.title ?? `Case ${r.id}`} · {r.role}</Link></li>)}</ul>{cursor && <button className="btn" disabled={busy} onClick={() => void run(async () => { const r = await request(`/api/leases?cursor=${cursor}`); setRows(old => [...old, ...r.items]); setCursor(r.nextCursor); })}>Load more</button>}</section>;
}
function NewLease() {
  const { request } = useLive(); const [profiles, setProfiles] = useState<Data[]>([]), [created, setCreated] = useState<Data | null>(null), [error, setError] = useState('');
  useEffect(() => { let alive = true; request('/api/resolver/profiles').then(r => { if (alive) setProfiles(r.items); }).catch(e => { if (alive) setError(e.message); }); return () => { alive = false; }; }, [request]);
  return <>{error && <p role="alert">{error}</p>}<Form title="Create a lease draft as landlord" fields={[{ name: 'title', label: 'Lease name' }, { name: 'deposit', label: 'Deposit (1–10,000 MockUSD, up to 2 decimal places)' }, { name: 'leaseStartAt', label: 'Lease start', type: 'datetime-local' }, { name: 'leaseEndAt', label: 'Lease end', type: 'datetime-local' }, { name: 'acceptDeadline', label: 'Acceptance & funding deadline', type: 'datetime-local' }, { name: 'serviceProfileId', label: 'Test service accepted by both resolvers', options: [{ value: '', label: 'Select a service' }, ...profiles.map(p => ({ value: p.id, label: `${p.id} · ${p.manifest.text}` }))] }, { name: 'termsText', label: 'Full terms (at least 20 characters)', type: 'textarea', minLength: 20 }]} submit="Save draft" disabled={!profiles.length} onSubmit={async v => { const depositAmount = units(v.deposit); if (BigInt(depositAmount) < 1000000n) throw new Error('The minimum deposit is 1 MockUSD'); setCreated(await request('/api/leases/drafts', { title: v.title, depositAmount, termsText: v.termsText, serviceProfileId: v.serviceProfileId, leaseStartAt: seconds(v.leaseStartAt), leaseEndAt: seconds(v.leaseEndAt), acceptDeadline: seconds(v.acceptDeadline) })); }}><p>A draft is not a deployed lease. Invite the tenant, then review the terms before creating the contract. A verified test service must be available to continue.</p></Form>{profiles.map(p => <Details key={p.id} title={`Test service ${p.id} — full rules`} value={p.manifest} />)}{created && <Link className="btn" href={`/leases/${created.id}`}>View draft & invite tenant</Link>}</>;
}
function Invite({ token }: { token: string }) {
  const { request, run, busy } = useLive(); const [preview, setPreview] = useState<Data | null>(null), [error, setError] = useState(''), [joined, setJoined] = useState(false);
  useEffect(() => { let alive = true; request(`/api/invites/${token}`).then(r => { if (alive) setPreview(r); }).catch(e => { if (alive) setError(e.message); }); return () => { alive = false; }; }, [token, request]);
  return <section className="glass glass-pad"><h1>Private lease invitation</h1>{error && <p role="alert">{error}</p>}{preview && <><p>Deposit {money(preview.depositAmount)}; lease ends <DateText value={preview.leaseEndAt} /></p><p>Joining links your current account to the draft. It does not accept the lease terms or deposit funds.</p>{joined ? <Link href={`/leases/${preview.leaseId}`}>View the full draft</Link> : <button className="btn" disabled={busy || !preview.walletMatches} onClick={() => void run(async () => { await request(`/api/invites/${token}/claim`, { confirm: true }); setJoined(true); })}>Join with this account</button>}</>}</section>;
}
function LeasePage({ id, caseId }: { id: string; caseId?: string }) {
  const { request, config, updated, wallet } = useLive();
  const [data, setData] = useState<Data | null>(null), [chain, setChain] = useState<Data | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [tick, setTick] = useState(0);
  const route = usePathname();
  const view = caseId ? 'case' : ['fund', 'checkout', 'claims', 'settlement'].find(section => route.endsWith('/' + section)) ?? 'overview';
  const refresh = useCallback(() => setTick(n => n + 1), []);
  useEffect(() => {
    let alive = true; setLoading(true); setError('');
    (async () => { const value = await request(caseId ? `/api/cases/${caseId}` : `/api/leases/${id}`); if (caseId && value.leaseId !== id) throw new Error('Case does not belong to this lease'); const snapshot = value.contractAddress ? await readLease(config, value.contractAddress, value.commitment) : null;
      if (snapshot) { const roleAddress = ({ T: 'tenant', L: 'landlord', R: 'primaryResolver', F: 'fallbackResolver' } as Record<string, string>)[value.role]; if (!roleAddress || snapshot.terms[roleAddress].toLowerCase() !== wallet?.address.toLowerCase()) throw new Error('On-chain participant does not match the signed-in account'); }
      if (alive) { setData(value); setChain(snapshot); }
    })().catch(e => { if (alive) { setError(e.message); if (e.status === 403 || e.status === 401) { setData(null); setChain(null); } } }).finally(() => { if (alive) setLoading(false); });
    return () => { alive = false; };
  }, [request, id, caseId, config, updated, tick, wallet?.address]);
  return <><h1>{data?.terms.title ?? 'Lease workspace'}</h1>{loading && <p>Reading confirmed on-chain state…</p>}{error && <p className="error" role="alert">Read failed: {error}. Last known balances are preserved. Financial actions are disabled.</p>}<button className="btn" onClick={refresh} disabled={loading}>Refresh</button>{data && <><LeaseNavigation id={id} role={data.role} view={view} /><p>Your role: {({ T: 'Tenant', L: 'Landlord', R: 'Primary resolver', F: 'Fallback resolver' } as Record<string, string>)[data.role]}</p>{chain && <section className="glass glass-pad"><h2>Confirmed on-chain balances</h2><div className="live-balances">{[['fundedAmount', 'Funded'], ['tenantCredit', 'Tenant claimable'], ['landlordCredit', 'Landlord claimable'], ['unallocated', 'Unallocated'], ['tenantWithdrawn', 'Tenant withdrawn to date'], ['landlordWithdrawn', 'Landlord withdrawn to date']].map(([k, label]) => <div key={k}><p>{label}</p><strong>{money(chain.accounting[k])}</strong></div>)}</div><p>Confirmed block {chain.blockNumber} · <DateText value={chain.chainTime} /></p>{Number(chain.phase) === 5 && <Estimate chain={chain} />}<Details title="Verify accounts, deadlines & contract" value={{ address: data.contractAddress, terms: chain.terms, schedule: chain.schedule, proposal: chain.proposal }} /></section>}
      <fieldset className="live-controls" disabled={loading || !!error}>{chain ? <><LeaseActions data={data} chain={chain} caseId={caseId} refresh={refresh} view={view} />{['checkout', 'case'].includes(view) && ['T', 'L'].includes(data.role) && BigInt(chain.accounting.fundedAmount) > 0n && Number(chain.phase) !== 11 && <Materials data={data} caseId={caseId} refresh={refresh} />}</> : <Draft data={data} refresh={refresh} />}</fieldset>
      {(data.cases ?? []).map((c: Data) => <p key={c.id}><Link href={`/leases/${id}/cases/${c.id}`}>Open case {c.chain_case_id} — evidence & resolution</Link></p>)}<History data={data} caseId={caseId} /><ExportGas leaseId={id} caseId={caseId} />
    </>}</>;
}
function Draft({ data, refresh }: { data: Data; refresh: () => void }) {
  const { request, run, busy, propose, config } = useLive(); const [invite, setInvite] = useState('');
  return <section className="glass glass-pad"><h2>Undeployed draft · Version {data.version}</h2><p>{data.terms.termsText}</p><p>Deposit {money(data.terms.depositAmount)}; Tenant {data.terms.tenant ?? 'Awaiting an invited tenant'}; Landlord {data.terms.landlord}</p><Details title="Full terms, deadlines, participants & service rules" value={data.terms} />{data.role === 'L' && <>
    {!data.terms.tenant && <button className="btn" disabled={busy} onClick={() => void run(async () => { const r = await request(`/api/leases/${data.id}/invites`, { expiresInSeconds: 86400 }); setInvite(`${window.location.origin}/invite/${r.token}`); })}>Create a 24-hour invitation</button>}{invite && <p>Share this private invitation with the intended tenant: <input aria-label="Private invitation link" readOnly value={invite} /></p>}
    {!data.frozen && <Form title="Edit draft terms" fields={[{ name: 'title', label: 'Name', value: data.terms.title }, { name: 'termsText', label: 'Full terms', type: 'textarea', minLength: 20, value: data.terms.termsText }]} submit="Save a new version" onSubmit={async v => { await request(`/api/leases/drafts/${data.id}`, { version: data.version, title: v.title, termsText: v.termsText }, 'PATCH'); refresh(); }} />}
    <button className="btn btn-primary" disabled={busy || !data.terms.tenant} onClick={() => void run(async () => { const prepared = await request(`/api/leases/drafts/${data.id}/prepare`, { version: data.version }); if (prepared.factory.toLowerCase() !== config.factory.toLowerCase() || prepared.chainId !== config.chainId || prepared.functionName !== 'createLease' || prepared.commitment !== data.commitment) throw new Error('Deployment parameters do not match the reviewed terms'); propose({ title: `Create ${money(data.terms.depositAmount)} deposit lease and accept the terms`, explanation: 'The draft is frozen. Creating the contract also accepts these terms as the landlord. The tenant must separately accept and fund it.', kind: 'factory', address: prepared.factory, functionName: 'createLease', args: prepared.args, leaseId: data.id }); })}>{data.frozen ? 'Continue creating the frozen lease' : 'Freeze draft & review contract creation'}</button>
    <Form title="Recover an existing deployment" fields={[{ name: 'hash', label: 'Original contract creation transaction hash' }]} submit="Verify & attach the confirmed deployment" onSubmit={async v => { await request(`/api/leases/${data.id}/deployment`, { transactionHash: v.hash }); refresh(); }}><p>If a transaction was already sent, check it and recover the record before creating another contract.</p></Form>
  </>}</section>;
}

function LeaseNavigation({ id, role, view }: { id: string; role: string; view: string }) {
  if (!['T', 'L'].includes(role)) return null;
  return <nav className="live-tabs" aria-label="Lease sections">{[['overview', 'Overview'], ['fund', 'Terms & deposit'], ['checkout', 'Checkout & evidence'], ['claims', 'Deductions'], ['settlement', 'Settlement']].map(([key, label]) => <Link key={key} href={`/leases/${id}${key === 'overview' ? '' : '/' + key}`} aria-current={view === key ? 'page' : undefined}>{label}</Link>)}</nav>;
}
function Estimate({ chain }: { chain: Data }) {
  const outstanding = chain.claims.filter((claim: Data) => Number(claim.status) !== 3) as Data[];
  const claimed = outstanding.reduce((sum, claim) => sum + BigInt(claim.amount), 0n);
  const accepted = outstanding.filter(claim => Number(claim.status) === 1).reduce((sum, claim) => sum + BigInt(claim.amount), 0n);
  return <div className="live-estimate"><h3>Estimated split — not yet claimable</h3><p>Tenant: {money(BigInt(chain.terms.depositAmount) - claimed)} · Landlord: {money(accepted)} · Awaiting response or resolution: {money(claimed - accepted)}</p><p>The claim window must close and allocation must be confirmed before these amounts become claimable. The estimate may change while claims and responses remain open.</p></div>;
}
