'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { formatMoney,parseMoney,validateDeposit } from '@rentbond/shared';
import { useRentBond } from '@/features/provider';
import { roleNames,stageNames,claimNames,type Lease,type Claim } from '@/features/model';
import { BalanceCard,Panel,Money,Deadline,ConfirmButton } from './controls';
import { liveWriteBlocker } from '@/features/transaction';

export function LeaseScreen({tab}:{tab:string}){
 const {lease:l,role,notice}=useRentBond();if(!l)return null;
 if(role==='fallback'&&l.case?.phase!=='Fallback')return <Panel title="当前没有授权案件"><p>备用处理人仅在案件升级后可访问该案材料。预授权服务不赋予全部租约访问权。</p></Panel>;
 if(role==='primary'&&!l.case)return <Panel title="当前没有分配的案件"><p>处理人不能浏览全部私人租约。</p></Panel>;
 const tabs=[['overview','工作台'],['fund','条款与存入'],['checkout','交接资料'],['claims','扣款与回应'],['cases','争议处理'],['settlement','结算与导出']];
 return <><div className="breadcrumbs"><Link href="/leases">我的租约</Link> / <span>{l.id}</span></div><div className="page-heading"><div><span className="eyebrow">REMOTE MOVE-OUT</span><h1>{l.title}</h1><p>入住前已采用的押金结算规则 · 当前视角：{roleNames[role]}</p></div><span className="badge">{stageNames[l.stage]}</span></div><nav className="tabs" aria-label="租约页面">{tabs.map(([v,t])=><Link key={v} className={tab===v?'active':''} href={`/leases/${l.id}/${v==='overview'?'':v}`}>{t}</Link>)}</nav>{notice&&<div role="status" className="notice">{notice}</div>}
 {tab==='overview'?<><BalanceCard lease={l}/><div className="two-columns"><Panel title="下一步" subtitle="先处理与你有关的动作"><h3>{l.stage==='ClaimsReview'?'回应剩余扣款，或领取已分配金额':stageNames[l.stage]}</h3><p>一项扣款有争议，不影响已经分配给你的余额。</p><div className="actions"><Link className="button" href={`/leases/${l.id}/claims`}>查看扣款清单 →</Link><Link className="button secondary" href={`/leases/${l.id}/settlement`}>查看领取</Link></div><Deadline value={l.responseDeadline} label="回应截止"/></Panel><Panel title="结算时间线" subtitle="当前为虚构案例记录"><ol className="timeline">{l.history.slice(-5).map((h,i)=><li key={`${h}-${i}`}>{h}</li>)}</ol></Panel></div><EvidencePanel lease={l}/></>:null}
 {(tab==='fund'||tab==='invite')&&<Funding lease={l}/>}
 {tab==='claims'&&<Claims lease={l}/>}
 {tab==='checkout'&&<Checkout lease={l}/>}
 {tab==='cases'&&<CasePanel lease={l}/>}
 {tab==='settlement'&&<Settlement lease={l}/>}
 <details className="technical"><summary>核验详情与固定规则</summary><p>MockUSD · 6位小数 · 业务步长0.01 · TIMEOUT_RETURN_UNAWARDED_TO_TENANT</p><Deadline value={l.leaseEndAt} label="担保截止 / 预定结算起点"/><Deadline value={l.hardEndAt} label="最迟退出日期"/><p>虚构预览无合约地址或交易哈希。{liveWriteBlocker}</p></details></>;
}
function Funding({lease:l}:{lease:Lease}){const {role}=useRentBond();return <div className="two-columns"><Panel title="共同确认押金规则" subtitle="邀请不是签约，确认同一条款后再存入"><div className="definition"><span>押金</span><strong><Money value={l.deposit}/></strong><span>处理服务</span><strong>演示方案 v1 · Robin / Taylor</strong><span>服务授权</span><strong>虚构示例中已预授权</strong><span>租客确认</span><strong>{l.accepted?'已确认（虚构）':'等待确认'}</strong></div><p>房东一次申报最多10项。租客不回应不视为同意，争议进入主备处理；无有效支持的争议金额按固定期限退租客，已支持款项保留。</p><Deadline value={l.hardEndAt} label="最迟退出日期"/><div className="actions"><ConfirmButton label="接受此份条款" description="确认当前金额、主备处理服务、期限及固定退出政策。此操作不能由邀请链接代替。" action={{type:'accept'}} disabled={role!=='tenant'||l.stage!=='AwaitingAcceptance'}/><ConfirmButton secondary label="取消未入金约定" description="取消后本约定不能再存入。" action={{type:'cancel'}} disabled={!['tenant','landlord'].includes(role)||BigInt(l.accounting.fundedAmount)>0n}/></div></Panel><Panel title="存入测试押金" subtitle="两个独立步骤，金额保持精确"><div className={`fund-step ${l.approved?'done':''}`}><b>1</b><div><h3>准备精确金额授权</h3><p>{l.approved?'授权已完成；不代表押金已经存入。':'只授权本次押金金额，不使用无限授权。'}</p></div></div><ConfirmButton label={`授权 ${formatMoney(l.deposit)} MockUSD`} description="允许收款合约提取本次精确押金。授权后仍须另行确认存入。" action={{type:'approve'}} disabled={role!=='tenant'||l.stage!=='AwaitingFunding'||l.approved}/><div className={`fund-step ${l.accounting.fundedAmount!=='0'?'done':''}`}><b>2</b><div><h3>确认存入</h3><p>{l.accounting.fundedAmount==='0'?'未存入。退出或取消不会自动进行下一步。':'示例已存入；真实模式必须等待链上确认。'}</p></div></div><ConfirmButton label={`存入 ${formatMoney(l.deposit)} MockUSD`} description="确认将测试押金存入固定租约合约。失败时不会显示已存入。" action={{type:'fund'}} disabled={role!=='tenant'||l.stage!=='AwaitingFunding'||!l.approved}/>{l.approved&&l.accounting.fundedAmount==='0'&&<ConfirmButton secondary label="撤销金额授权" description="将授权额度恢复为零。" action={{type:'revokeApproval'}} disabled={role!=='tenant'}/>}<p className="muted">测试费用补给及真实交易由 B/D/E 联调后启用。当前没有扣款。</p></Panel></div>;}

function Claims({lease:l}:{lease:Lease}){
 const {role}=useRentBond();const [reason,setReason]=useState('入住清单已记录该划痕，我不认可这项新增损坏扣款。');const [draft,setDraft]=useState<Claim[]>([{id:0,title:'退租清洁',amount:'100000000',reason:'退租时厨房清洁未达到双方约定标准，需安排额外清洁。',clause:'4.1 清洁',evidence:'无票据；按报价说明依据',status:'Pending'}]);
 const canRespond=role==='tenant'&&['ClaimsOpen','ClaimsReview'].includes(l.stage)&&Date.now()/1000<l.responseDeadline;
 return <><BalanceCard lease={l}/><div className="two-columns wide"><div><Panel title="逐项审核扣款" subtitle="认可需要单独确认，争议不要求你必须提供照片">{l.claims.length===0?<p className="empty-inline">暂无已提交清单。</p>:l.claims.map(c=><article className="claim-card" key={c.id}><div className="claim-heading"><div><span className="badge">{claimNames[c.status]}</span><h3>{c.title}</h3></div><Money value={c.amount}/></div><p>{c.reason}</p><dl><dt>对应条款</dt><dd>{c.clause}</dd><dt>证据 / 费用依据</dt><dd>{c.evidence}</dd></dl>{canRespond&&['Pending','Disputed'].includes(c.status)&&<div className="actions"><ConfirmButton label={`认可 ${formatMoney(c.amount)} MockUSD`} description={`认可「${c.title}」后不能撤回。申报窗口关闭前只记录认可，关闭后才能分配。`} action={{type:'respond',id:c.id,accept:true,reason:''}}/><ConfirmButton secondary label={`争议「${c.title}」`} description="该部分保持未分配，进入预定处理；其余已分配余额不受影响。" action={{type:'respond',id:c.id,accept:false,reason}}/></div>}{role==='landlord'&&['ClaimsOpen','ClaimsReview'].includes(l.stage)&&!['Allocated','Waived'].includes(c.status)&&<ConfirmButton secondary label={`撤回「${c.title}」`} description="撤回的尚未分配金额将按申报窗口规则归租客。" action={{type:'waive',id:c.id}}/>}</article>)}{canRespond&&<label>异议说明<textarea aria-label="异议说明" value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000}/></label>}</Panel>
 {role==='landlord'&&!l.claimsSubmitted&&l.stage==='ClaimsOpen'&&<Panel title="准备一次性扣款清单" subtitle="提交后不能新增或提高金额，最多10项">{draft.map((c,i)=><fieldset key={i}><legend>项目 {i+1}</legend><label>名称<input value={c.title} onChange={e=>setDraft(d=>d.map((v,j)=>j===i?{...v,title:e.target.value}:v))}/></label><label>金额（MockUSD）<input inputMode="decimal" defaultValue={(BigInt(c.amount)/1000000n).toString()} onChange={e=>{try{const amount=parseMoney(e.target.value).toString();setDraft(d=>d.map((v,j)=>j===i?{...v,amount}:v));e.target.setCustomValidity('');}catch{e.target.setCustomValidity('金额格式错误');setDraft(d=>d.map((v,j)=>j===i?{...v,amount:'0'}:v));}}}/></label><label>理由（20—2000字）<textarea value={c.reason} onChange={e=>setDraft(d=>d.map((v,j)=>j===i?{...v,reason:e.target.value}:v))}/></label><label>条款<input value={c.clause} onChange={e=>setDraft(d=>d.map((v,j)=>j===i?{...v,clause:e.target.value}:v))}/></label><label>票据 / 无票据依据<input value={c.evidence} onChange={e=>setDraft(d=>d.map((v,j)=>j===i?{...v,evidence:e.target.value}:v))}/></label></fieldset>)}<div className="actions"><button className="secondary" disabled={draft.length>=10} onClick={()=>setDraft(d=>[...d,{id:d.length,title:'新扣款项',amount:'0',reason:'',clause:'',evidence:'',status:'Pending'}])}>添加项目</button><ConfirmButton label="提交最终扣款清单" description="确认后不能新增项目或提高金额。" action={{type:'claims',claims:draft}}/></div></Panel>}</div>
 <aside><Panel title="窗口与资金释放"><Deadline value={l.claimDeadline} label="申报截止"/><Deadline value={l.responseDeadline} label="回应截止"/><p>{l.stage==='ClaimsOpen'?'当前拆分仅为预计。未申索金额在窗口关闭后才能分配。':'已分配金额可独立领取，不必等待争议结束。'}</p><div className="stack"><ConfirmButton label="关闭申报并分配" description="仅在申报截止后，分配未申索和已认可／撤回的金额。" action={{type:'closeClaims'}} disabled={l.stage!=='ClaimsOpen'||Date.now()/1000<l.claimDeadline}/><ConfirmButton secondary label="开启剩余争议案件" description="回应截止后，剩余有效申索形成一个金额快照，普通回应与撤回停止。" action={{type:'openCase'}} disabled={l.stage!=='ClaimsReview'||Date.now()/1000<l.responseDeadline||l.accounting.unallocated==='0'}/></div></Panel><div className="tip"><b>不回应 ≠ 同意</b><p>回应期结束仍未回应的项目进入处理，不自动分配给房东。</p></div></aside></div></>;
}

function EvidencePanel({lease:l}:{lease:Lease}){const {role}=useRentBond();const [name,setName]=useState('');const [description,setDescription]=useState('');const [fileError,setFileError]=useState('');const party=['tenant','landlord'].includes(role);return <Panel title="交接与材料记录" subtitle="单方提交不等于双方认可；材料哈希不证明内容真实"><div className="evidence-list">{l.evidence.map(e=><article key={e.id}><span className="file-icon">▤</span><div><h3>{e.name} <small>v{e.version}</small></h3><p>{e.description}</p><small>{roleNames[e.author]} · {e.stage} · {new Date(e.createdAt*1000).toLocaleDateString('zh-CN')}</small><p className="badge">{{saved:'已保存，待提交记录',submitted:'单方已提交，等待回应',accepted:'双方已认可本版本',disputed:'对方对本版本有异议'}[e.state]}</p></div><div className="stack">{e.author===role&&e.state==='saved'&&<ConfirmButton secondary label="提交此版本记录" description="提交后不可覆盖，后续材料应新增版本。" action={{type:'submitEvidence',id:e.id}}/>}{party&&e.author!==role&&e.state==='submitted'&&<><ConfirmButton secondary label="认可此版本" description="仅认可当前精确版本，新版本不继承认可。" action={{type:'ackEvidence',id:e.id,agree:true}}/><ConfirmButton secondary label="对此版本有异议" description="记录对当前版本的异议。" action={{type:'ackEvidence',id:e.id,agree:false}}/></>}</div></article>)}</div>{party&&!['Closed','Cancelled'].includes(l.stage)&&<details><summary>添加新的材料说明</summary><label>名称<input value={name} onChange={e=>setName(e.target.value)}/></label><label>说明<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>检查文件格式（预览不上传）<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>{const f=e.target.files?.[0];setFileError(f&&(!['image/jpeg','image/png','application/pdf'].includes(f.type)||f.size>10*1024*1024)?'只支持 JPG / PNG / PDF，单文件最多10MB':f?'格式检查通过。当前不读取或上传文件内容；仅保存下面的虚构说明。':'');}}/></label><p role="status">{fileError}</p><ConfirmButton label="保存材料说明" description="仅新增当前内存中的说明，尚未提交证据记录。实际文件上传等待私有存储接口。" action={{type:'evidence',name,description,stage:'退租'}}/></details>}</Panel>;}

function Checkout({lease:l}:{lease:Lease}){const {role}=useRentBond();const [date,setDate]=useState(new Date().toISOString().slice(0,10));const [evidence,setEvidence]=useState('退租清单 v1');return <><div className="two-columns"><Panel title="确认房屋交接" subtitle="交接确认开启申报窗口，不直接决定押金归属"><Deadline value={l.leaseEndAt} label="约定结算日期"/><label>实际交接日期（UTC）<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>材料引用<input value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><div className="actions"><ConfirmButton label="请求交接确认" description="另一方可认可或提出异议。无人回应不立即退款。" action={{type:'checkout',date:Date.parse(`${date}T00:00:00Z`)/1000,evidence}} disabled={!['tenant','landlord'].includes(role)||l.stage!=='Active'}/>{l.stage==='CheckoutRequested'&&role!==l.checkoutBy&&['tenant','landlord'].includes(role)&&<><ConfirmButton label="认可交接" description="从有效确认时刻启动固定申报窗口。" action={{type:'checkoutRespond',agree:true}}/><ConfirmButton secondary label="交接有异议" description="交接争议不分配押金。正式 CHECKOUT 案件需 B 的接口联调；预定结算日期保持不变。" action={{type:'checkoutRespond',agree:false}}/></>}</div></Panel><Panel title="失联或未完成交接"><p>到约定日期可公开启动押金结算。晚调用不会重新计算窗口，也不意味着租赁关系自动终止。</p><ConfirmButton label="按约定日期启动结算" description="使用固定 leaseEndAt 起算，不从当前操作时间延后。" action={{type:'startScheduled'}} disabled={Date.now()/1000<l.leaseEndAt||!['Active','CheckoutRequested'].includes(l.stage)}/><p className="muted">完整 CHECKOUT 案件入口待生成 ABI 和案件接口。此处不将异议伪装成确认。</p></Panel></div><EvidencePanel lease={l}/></>;}

function CasePanel({lease:l}:{lease:Lease}){
 const {role}=useRentBond();const [amounts,setAmounts]=useState<Record<number,string>>({1:'50'});const [reason,setReason]=useState('根据双方入住清单和退租资料，旧划痕部分不支持扣款，支持修复费用50 MockUSD。');const c=l.case;
 if(!c)return <Panel title="尚无争议案件"><p>回应截止后仍有未分配申索时，可在扣款页创建案件。未回应不自动判任一方胜诉。</p><Link className="button secondary" href={`/leases/${l.id}/claims`}>查看扣款与期限</Link></Panel>;
 const now=Date.now()/1000;const primary=role==='primary'&&['Primary','Evidence'].includes(c.phase)&&now>=c.evidenceDeadline&&now<c.primaryDeadline;const fallback=role==='fallback'&&c.phase==='Fallback'&&now>=c.fallbackStartAt+2*86400&&now<c.fallbackDeadline;
 return <><div className="two-columns"><Panel title={`案件 ${c.id}`} subtitle={`${c.type==='CLAIMS'?'扣款争议':'交接确认'} · ${c.phase}`}><h3>当前尚未分配 <Money value={l.accounting.unallocated}/></h3><p>主结果有挑战期；备用处理仅在升级后获得该案访问权限。</p>{c.decision&&<div className="result-box"><span className="badge">{c.phase==='Proposed'?'主结果已提出，尚未生效':'处理结果'}</span><h3>建议分给房东 <Money value={c.decision}/></h3><p>{c.decisionReason}</p></div>}{(primary||fallback)&&<><>{l.claims.filter(item=>!["Allocated","Waived"].includes(item.status)).map(item=><label key={item.id}>{item.title}：给房东的金额（上限 {formatMoney(item.amount)}）<input value={amounts[item.id]??"0"} inputMode="decimal" onChange={e=>setAmounts(v=>({...v,[item.id]:e.target.value}))}/></label>)}</><label>处理理由<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><ConfirmButton label={primary?'提出主处理结果':'提交备用最终结果'} description={primary?'提出后不立即分配；双方有固定挑战期。':'仅在备用补充材料期结束后可给出最终结果，金额不得超过申索快照。'} action={()=>({type:'decision',amounts:l.claims.filter(item=>!['Allocated','Waived'].includes(item.status)).map(item=>({id:item.id,landlordShare:parseMoney(amounts[item.id]??'0').toString()})),reason})}/></>}<div className="actions"><ConfirmButton secondary label="挑战主结果" description="升级备用处理，原主结果不能再生效。" action={{type:'challenge'}} disabled={!['tenant','landlord'].includes(role)||c.phase!=='Proposed'||now>=c.challengeDeadline}/><ConfirmButton label="使主结果生效" description="挑战期已结束且无人挑战时，才按结果分配。" action={{type:'finalize'}} disabled={c.phase!=='Proposed'||now<c.challengeDeadline}/></div></Panel><Panel title="固定期限与后续路径"><Deadline value={c.evidenceDeadline} label="主阶段证据截止"/><Deadline value={c.primaryDeadline} label="主处理截止"/>{c.challengeDeadline>0&&<Deadline value={c.challengeDeadline} label="挑战截止"/>}{c.fallbackDeadline>0&&<Deadline value={c.fallbackDeadline} label="备用处理截止"/>}{c.timeoutAt>0&&<Deadline value={c.timeoutAt} label="服务退出日期"/>}<div className="stack"><ConfirmButton secondary label="主处理超时，升级备用" description="备用起点固定为原主处理截止，迟操作不能延长期限。" action={{type:'escalate'}} disabled={!['Primary','Evidence'].includes(c.phase)||now<c.primaryDeadline}/><ConfirmButton secondary label="标记备用服务超时" description="进入退出等待期，不立即释放未到退出日期的争议余额。" action={{type:'serviceTimeout'}} disabled={c.phase!=='Fallback'||now<c.fallbackDeadline}/><ConfirmButton label="按退出规则结算" description="只把无有效支持的争议款给租客，已分配和已领取金额保留。" action={{type:'timeout'}} disabled={c.phase!=='ExitPending'||now<c.timeoutAt}/></div></Panel></div><EvidencePanel lease={l}/></>;
}

function Settlement({lease:l}:{lease:Lease}){const {role}=useRentBond();const [tenant,setTenant]=useState('150');const [landlord,setLandlord]=useState('50');const [exported,setExported]=useState(false);const party=['tenant','landlord'].includes(role);const credit=role==='tenant'?l.accounting.tenantCredit:l.accounting.landlordCredit;
 function exportFixture(){const blob=new Blob([JSON.stringify({fixtureOnly:true,notice:'虚构前端数据，不是正式租约证据或链上记录',lease:l},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='rentbond-fictional-preview.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setExported(true);}
 return <><BalanceCard lease={l}/><div className="two-columns"><Panel title="领取属于你的余额" subtitle="已分配不代表已经到账"><h2><Money value={party?credit:'0'}/></h2><p>{party?`领取到固定${role==='tenant'?'租客':'房东'}地址，不能修改受益人。`:'处理人不能领取押金。'}</p><ConfirmButton label={`领取 ${formatMoney(party?credit:'0')} MockUSD`} description="确认领取到自己的固定地址。转账失败不能损失可领取余额。" action={{type:'withdraw'}} disabled={!party||BigInt(credit)===0n}/><div className="definition"><span>租客累计已领取</span><Money value={l.accounting.tenantWithdrawn}/><span>房东累计已领取</span><Money value={l.accounting.landlordWithdrawn}/></div><p className="muted">当前为虚构预览，不生成假的交易哈希或区块浏览器链接。</p></Panel><Panel title="共同和解剩余金额" subtitle="仅对尚未分配部分和解，不重复分配已领取余额"><label>租客金额<input inputMode="decimal" value={tenant} onChange={e=>setTenant(e.target.value)}/></label><label>房东金额<input inputMode="decimal" value={landlord} onChange={e=>setLandlord(e.target.value)}/></label><ConfirmButton label="提出共同和解" description="只结清工具中的剩余押金，不自动放弃合同以外权利。另一方必须确认同一有效版本。" action={()=>({type:'settle',tenantShare:parseMoney(tenant).toString(),landlordShare:parseMoney(landlord).toString(),validUntil:Math.min(Math.floor(Date.now()/1000)+3600,l.hardEndAt,l.case?.timeoutAt||l.hardEndAt)})} disabled={!party||l.accounting.unallocated==='0'}/>{l.settlement&&<div className="result-box"><p>租客 <Money value={l.settlement.tenantShare}/> / 房东 <Money value={l.settlement.landlordShare}/></p><p>{l.settlement.revision===l.revision?'等待另一方确认':'状态已改变，旧提案失效，请重新提出'}</p><ConfirmButton label="确认共同和解" description="确认当前提案、金额和有效版本，完成后旧案件与结果失效。" action={{type:'confirmSettlement'}} disabled={!party||l.settlement.by===role||l.settlement.revision!==l.revision}/></div>}</Panel></div><Panel title="退出与资料导出"><Deadline value={l.hardEndAt} label="最迟退出日期"/><div className="actions"><ConfirmButton label="执行最终期限退出" description="先尊重已成立的有效金额权利，再将剩余无有效支持金额退租客；不修改已有可领取余额。" action={{type:'expire'}} disabled={Date.now()/1000<l.hardEndAt||l.accounting.unallocated==='0'}/><button className="secondary" onClick={exportFixture}>下载虚构预览记录</button></div>{exported&&<p role="status">已生成带 fixtureOnly 标记的虚构记录。正式私有资料导出待 D 的异步接口。</p>}</Panel></>;
}

export function ResolverList(){const {role,lease:l}=useRentBond();const authorized=l?.case&&((role==='primary'&&['Evidence','Primary','Proposed'].includes(l.case.phase))||(role==='fallback'&&l.case.phase==='Fallback'));return <><div className="page-heading"><div><span className="eyebrow">RESOLUTION DESK</span><h1>我的处理案件</h1><p>仅查看当前阶段分配给你的案件。</p></div></div><Panel title={authorized?'待处理案件':'没有授权案件'}>{authorized?<Link className="lease-list-card" href={`/leases/${l.id}/cases/${l.case!.id}`}><div><span className="badge">{l.case!.phase}</span><h2>{l.title}</h2><p>尚未分配 <Money value={l.accounting.unallocated}/></p></div><strong>打开案件 →</strong></Link>:<p>当事人不能作处理人。备用处理人须等待正式升级，不因服务预授权获得所有案件资料。</p>}</Panel></>;}

export function CreateLease(){const s=useRentBond();const router=useRouter();const [amount,setAmount]=useState('1000');const [title,setTitle]=useState('远程退租押金约定');const [date,setDate]=useState('');const [accepted,setAccepted]=useState(false);const [error,setError]=useState('');const [ready,setReady]=useState(false);return <><div className="page-heading"><div><span className="eyebrow">NEW AGREEMENT</span><h1>创建押金约定</h1><p>先邀请租客关联账户，双方检查条款后再部署与入金。</p></div></div><div className="two-columns"><Panel title="1. 填写约定"><form onSubmit={e=>{e.preventDefault();setError('');try{validateDeposit(parseMoney(amount));if(!title.trim()||!date||Date.parse(date)<=Date.now())throw new Error('请填写名称及未来租期结束日');if(!accepted)throw new Error('请确认测试范围');setReady(true);}catch(err){setReady(false);setError((err as Error).message);}}}><label>约定名称<input required value={title} onChange={e=>{setTitle(e.target.value);setReady(false);}}/></label><label>押金（MockUSD）<input required inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setReady(false);}}/></label><label>租期结束日（UTC）<input required type="date" value={date} onChange={e=>{setDate(e.target.value);setReady(false);}}/></label><label>处理服务<select defaultValue=""><option value="" disabled>等待有效测试服务方案</option>{s.mode==='demo'&&<option value="demo">演示方案 v1（虚构）</option>}</select></label><label className="check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>我理解这不接收真实资产，且必须在入金前双方确认。</label><button>校验草稿</button>{error&&<p role="alert" className="error">{error}</p>}{ready&&<div role="status" className="notice">草稿校验通过，未保存、未部署。{s.mode==='demo'?'下方可打开预设1,000 MockUSD邀请示例；不是刚填写的草稿。':'真实草稿保存和邀请等待 D 的接口。'}</div>}</form></Panel><Panel title="2. 邀请与条款预览"><p>普通用户不需要手工输入租客长地址。租客使用私有邀请关联本人账户，房东再审阅双方身份与服务方案。</p><p>默认最迟退出日期为约定租期结束后37天。未回应进入处理，不自动判任何一方获胜。</p>{s.mode==='demo'&&<button className="secondary" onClick={()=>{s.reset('funding');router.push('/invite/demo-invite');}}>打开预设邀请示例</button>}<p className="muted">当前无真实草稿保存、邀请发出或链上部署。{liveWriteBlocker}</p></Panel></div></>;}
